### PR TITLE
Right button drag to delete highlights

### PR DESCRIPTION
**Pull request by MatanZ**
This changes highlight drawing behaviour:
 * Only left button dragging now draws highlights
 * Right button dragging deletes intersecting highlights
 * Dragging with other buttons does nothing

The function segment_intersect() is not fully correct. It does not work correctly
with colinear segments, but I chose this approach since performance might be crucial.

This can be considered a part of the #68 project.

After this patch the undo button is misnamed - it deletes the last drawn highlight, instead of undoing last action.

### CODE REVIEW

**Comment by Cimbali** [comment]
I think the proposition in #68 of an eraser mode is more intuitive than using right-click.

Also not sure if we want to maintain undoing of erasing, that means that erasing is just adding a layer of the background on top (or a layer that makes layers below become transparent).

**Comment by MatanZ** [comment]
I will add eraser option in addition to right button.

Undo is done like this: scribbler object has an undo stack. When an undoable action happens, the object is added to the undo stack, then undo pops the last from the stack, adds it to the list of scribbles if the operation was delete, or removes if the operation was draw.

**Comment by MatanZ** [comment]
I added erase mode which allows erasing by left button dragging.

I am not sure about the correct semantics: erase mode requires scribbling mode, so now if enable_erasing() is called when scribbling mode is disabled, it also enables this mode. (and the corresponding disable_erasing will also disable scribbling mode).
return self.scribbler.switch_erasing()
If the UI only calls this function when scribbling is enabled, then this does not matter.

I did not add any UI, as I do not know exactly how to add neither keyboard shortcuts nor GUI elements. For testing I added `return self.scribbler.switch_erasing()`  to the `if comman=="zoom"` statement in ui.py.

**Comment by Cimbali** [comment]
There is now an eraser preset just like the other pen presets.

**Pull request closed without merging**
