### PR TITLE
Scribble

### PR DESCRIPTION
**Pull request by Cimbali**
Would somebody care to test and tell me what they think of this implementation of writing on the projector screen? Maybe  @Epithumia who suggested it?

### CODE REVIEW

**Comment by Epithumia** [comment]
I'm getting the following error when running it:
```
Traceback (most recent call last):
File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\lib\site-packages\pympress-0.6-py3.4.egg\pympress\__main__.py", line 34, in <module>
  File "C:\Python34\lib\site-packages\pympress-0.6-py3.4.egg\pympress\util.py", line 52, in get_resource_path
  File "C:\Python34\lib\site-packages\pkg_resources\__init__.py", line 1161, in resource_filename
    self, resource_name
  File "C:\Python34\lib\site-packages\pkg_resources\__init__.py", line 1862, in get_resource_filename
    return self._extract_resource(manager, zip_path)
  File "C:\Python34\lib\site-packages\pkg_resources\__init__.py", line 1883, in _extract_resource
    timestamp, size = self._get_date_and_size(self.zipinfo[zip_path])
KeyError: 'pympress\\share\\locale'
```

**Comment by Cimbali** [comment]
That's strange, it seems your install can't find the translation files, but it looks in the right place. I've merged the fixes from master into this branch, can you try running the setup again?

Or if you install from pip, you can try `pip install -e git+https://github.com/Cimbali/pympress@scribble#egg=pympress`

There's at least one background problem when I tested it on windows, the "@bg_color" in the css doesn't seem to do anything.

**Comment by Epithumia** [comment]
Seems running `python setup.py install` doesn't move everything it should, `python setup.py develop` works.

I noticed there are two cancel buttons (both named "cancel") in highlight mode, I found one gets out of highlight mode, and one clears the highlights from the slide, but they should be named differently ("exit highlight mode" and "clear highlights") for example. Clicking highlight or next/previous also exits highlight mode.

The highlight function responds well, and the color selector is nice. The pen size slider is a little small it feels, maybe it could be vertical instead of horizontal.

The main limitation at the moment is that exiting highlight mode clears the highlight from the slide, which would prevent checking one's notes/annotations without losing highlights. Ideally, they should be persistent while pympress is open (so that if you go back/forward, they aren't lost) or at the very least while you are still on the slide (to be able to check notes/annotations), or if the "clear highlight" is pressed on a given slide.

**Comment by Cimbali** [comment]
The second button is supposed to be "undo" and the first one "exit" but they get default labels from the Gtk theme. This should be better.

I've added more persistent highlighting and a clear button, but the background issue and resizing the toolbar when a window is too small to contain it should still be fixed.

**Comment by Epithumia** [comment]
The persistent (until you chage slide) highlight works nice.

I'm not sure what the toolbar resizing and background issues were though. On the lastest commit, the highlight controls show over the presenter window as if the background is transparent, which is fine with me: http://imgur.com/a/FjRqk

However I noticed that resizing my windows throws errors:
```
AttributeError: 'module' object has no attribute 'vlcvideo'
Traceback (most recent call last):
  File "c:\users\endless\documents\pympress\pympress\ui.py", line 1035, in <lambda>
    self.c_overlay.foreach(lambda child, *ignored: child.resize() if type(child) is pympress.vlcvideo.VLCVideo else None, None)
AttributeError: 'module' object has no attribute 'vlcvideo'
```

**Comment by Cimbali** [comment]
Ah you probably also have a message saying video support is disabled, basically some error happened when importing the vlcvideo module.

There's no real portable way of catching exceptions with both python 2 and 3, but if you can modify the try/catch around the "import pympress.vlcvideo" at the beginning, we could know what the problem is. If you don't have vlc installed (or with a different fitness than python) that is most probably the cause.

**Comment by Cimbali** [comment]
The background is meant to be opaque, no you don't see the slide and thumbnails in the back (but still the bottom bar). However in the CSS you have to specify the colour and that changes per gtk theme, so I haven't found a good way p doing that yet.

Also I see your gtk is in French from the buttons, however python doesn't seem to pick that up which looks a little awkward. Probably a windows thing.

**Comment by Epithumia** [comment]
I installed VLC to check, and the error went away.

Background: a quick test seems to indicate that @theme_bg_color is what you want, not @bg_color.

Language: gtk must rely on keyboard settings to infer language, because my windows is set to use english for the language but french for the keyboard.

**Comment by Cimbali** [comment]
OK thanks for the research, it seems to work so I pushed it - I'll do more tests later.

**Pull request merged**
