### PR TITLE
Suggestions

### PR DESCRIPTION
**Pull request by Epithumia**
I just discovered that you forked and resumed work on pympress, which is excellent news. I have three suggestions to make for functionality I'd like to see added. At first glance, my first two suggestions shouldn't be too complex to implement, and the third one is probably on a much larger scale.

1. In note mode, the right side of the presenter screen could display a copy of the presentation screen in place of annotations. That is, show not just the next slide, but also the current slide. Typically, beamer notes embed such a preview in a vignette, but it is way too small to be useful, and having a dedicated frame would allow to have note themes without the vignette.
There should probably be a setting+shortcut so that one can opt to display annotations or current slide. In the same vein, having a shortcut to swap current slide<->notes would be good. I'd try and get that done or at least started, but at the moment, I only have a ubuntu 12.04 VM, and pympress fails to start ("gi._glib.GERrror: default.css:15:17: Junk at end of value", which as far as I can tell, is a version problem with GTK+3 since 12.04 has libgtk-3.0 3.4.1 and I'll need >3.12), which makes testing complicated. Once I get something running, I'll add to this issue once I have made changes and tests.

2. Touch mode. At least have <- and -> buttons on the presenter screen so the presentation can be moved backward/forward using a touch screen. I figure the bottom area has space for them if needed.

3. Live annotations. There are times when I want to draw on the slides as I give my presentation. That feature would probably require a lot more work but would set pympress a cut above all the other pdf presentation tools.

### CODE REVIEW

**Comment by Epithumia** [comment]
There you go, this PR is my implementation of suggestion 1: it adds a thumbnail for the current slide when in "Notes" mode (and it responds to the toggle switch), and makes the annotation space a frame that can be toggled off/on (shortcut: "a" or from the menu).

**Comment by Cimbali** [comment]
I'll review your PR properly later, but just a quick reply off the top of my head first. Per suggestion:

1) There are already 2 alternatives: 
- make your thumbnail bigger in your notes slide. I usually have it around 80% of the full notes slide, so no trouble seeing.
- use PDF annotations instead of beamer "notes"

The main issue that splitting the screen 3-way (notes, current, next) is that the "notes" slide could end up being small.

We probably don't need both the annotations frame and "notes" slide at the same time.

In general I'm not sure how customisable we can make the presenter window before we need a setup phase to ask the user how he wants it to look.

2&3) what kind of medium are you using? Some sort of tablet to control the presentation? Or some sort of interactive screen display instead of a projector?

2) Buttons left/right of the slide number could work. Have to see how it looks etc.

3) That sounds really cool & exciting and could make for more interactive presentations, but I'm not sure how it would work. Do you intend to draw on the presenter window, have it displayed on screen (content window)? Draw on the content window directly?
That sounds more like a "touch" feature as well, drawing live with a mouse feels rather clumsy.

**Comment by Epithumia** [comment]
1) Concerning alternatives

- Having a huge thumbnail means little space for notes, and I often have full note slides already, so it doesn't work for me
- LaTeX+Beamer doesn't generate annotations, and I'm not going to manually enter them on the 400ish slides that make the course I teach ;)

In essence, the screen is already 3 (4) way split: presenter slide (either copy or notes), next slide, annotations (and bottom bar). Since using notes means you likely won't use annotations, I made it so you can hide/show them, so in the (I expect) rare case of notes+annotations, the screen is 4 way split, and if you don't use annotations, it's the usual 3 way split.

2&3) I use an hybrid laptop (touch screen), either a t100ha (screen can be unhinged and used as a tablet) or a t101mt (screen can swivel to rest over the keyboard to use as a tablet)

3) I'm thinking how powerpoint does it. In PP, the presenter window has a large copy of the content slide and an area below for annotations, and you can draw on the presenter side content and it will be drawn simultaneously on the content screen. I couldn't find any good video showcasing it, but this one shows where the tools are found in presenter mode: https://www.youtube.com/watch?v=E9xGCZOL3QQ
The main appeal (to me) for that is to draw simple shapes (circle/underline/cross something, draw arrows). It's certainly doable in LaTeX+beamer (I do it) but it isn't as interactive.

**Comment by Cimbali** [comment]
Aha, now I've had time to test it, it doesn't look bad. The new "current slide" doesn't have its aspect ratio updated however, so that needs to be fixed.

Maybe the default behaviour for "notes" mode should be to disable the Annotations frame (and leave it togglable), so that without explicitly pressing A we never split the right column in three.

**Comment by Cimbali** [comment]
@Epithumia both suggestions 1 and 2 are now in master, feel free to check them out. I'm looking at feasibility of scribbles on screen.

**Comment by Epithumia** [comment]
There are errors in setup.py: line 30 has an open bracket that's never closed, and line 64 is missing a closing parenthesis.

Other than that: 

I noticed (on w10, using the latest master commit minus setup.py, python 3.4.4) that there are occasional mini-freezes when changing slide (the screen will pause for a second, and if quickly moving forward X slides, it might pause then jump X slides forward), which I don't remember having on the compiled windows version, but it might be my touch laptop not being as powerful as my pc or the fact it's running uncompiled.

The elements on the presenter screen look fine in notes mode, and the buttons respond correctly in big button mode.

**Comment by Cimbali** [comment]
I've only seen freezes when going through slides very fast and rendering non-cached slides. If that's the case you can try to increase the amount of prerendered slides, in the config file. If it's something else I'll have to look at it.

I must've been doing something else when I modified that setup.py, those are really dumb mistakes. I've corrected them now.

Have a look at the scribble branch as well, I implemented your third suggestion as I was a little bored this week-end. I'm not sure if it looks/feels exactly right;

**Pull request merged**
