### PR TITLE
Translation update

### PR DESCRIPTION
**Pull request by Cimbali**

### CODE REVIEW

**Comment by Cimbali** [comment]
@polaksta @multiflexi Can you translate the 4 missing strings in Polish and Czech ?
@FriedrichFroebel @susobaco Can you double-check my German and Spanish translations ?

Thanks

**Comment by FriedrichFroebel** [comment]
I would change the following strings:

```
msgid "GtkImage gif player"
msgstr "Gif-Wiedergabe mit GtkImage"

msgid "Media support uses {}."
msgstr "Videounterstützung verwendet {}."

msgid "Resources are loaded from "
msgstr "Daten werden geladen von "

msgid "_Undo zoom"
msgstr "Zoom z_urücksetzen"
```

If I did not miss anything, the remaining strings should be okay.

**Comment by Cimbali** [comment]
Good thing I asked. Thanks @FriedrichFroebel 

@polaksta  Thanks ! There are a few more strings I believe. "Resources are loaded from ", "_Zoom in" and "_Undo zoom"

**Comment by Cimbali** [comment]
Thanks ! Will merge and update soon.

**Comment by susobaco** [comment]
For Spaniah language:
msgid "GtkImage gif player"
msgstr "Reproductor de Gif GtkImage"
msgid "Media support uses {}."
msgstr "Usos de soporte de medios {}."
msgid "_Undo zoom"
msgstr "_Deshacer zoom"
msgid "_Zoom in"
msgstr "_Hacer zoom"
msgid "Resources are loaded from "
msgstr "Los recursos se cargan desde "

**Pull request merged**
